/**
 * DATA: CMS Contentful Page (EN)
 * Route: /en/geo-seo-agency/cms/contentful
 *
 * English version adapted for the international Contentful headless CMS market.
 * Content based on LLM auto-test (March 2026) and global Contentful ecosystem.
 */

import type { CmsPageData } from '@/types/sector-pages';

const data: CmsPageData = {
  // ============================================
  // SEO
  // ============================================
  seo: {
    slug: 'contentful',
    title: 'Contentful SEO & GEO Agency - Rankwell',
    description:
      'Rankwell optimizes SEO and AI visibility (GEO) for Contentful websites. Content modeling, SSR/SSG rendering, schema.org, Fastly CDN performance: a complete methodology built for Contentful.',
  },

  // ============================================
  // BLOC 1: HERO
  // ============================================
  hero: {
    breadcrumb: [
      { label: 'Home', href: '/' },
      { label: 'GEO & SEO Agency', href: '/en/geo-seo-agency' },
      { label: 'CMS & Platforms', href: '/en/geo-seo-agency/sectors' },
      { label: 'Contentful' },
    ],
    title: 'Contentful SEO & GEO: Rankings and AI Visibility',
    subtitle:
      'Contentful separates content from presentation: SEO depends entirely on the frontend rendering layer (Next.js, Gatsby, Nuxt) and on rigorous content modeling. Our experts combine technical SEO and GEO so your headless architecture ranks on Google and gets cited by AI engines.',
    ctaText: 'Request a Contentful SEO & GEO audit',
    ctaHref: '/en/contact',
  },

  // ============================================
  // BLOC 2: Why SEO is different on Contentful (IntroService)
  // ============================================
  whyDifferent: {
    title: 'Why SEO is different on Contentful',
    seoStrengths:
      '<strong class="text-secondary dark:text-accent">Contentful powers over 4,000 enterprises including 30% of the Fortune 500</strong>. Typed content modeling enables automatic schema.org generation via the frontend, and the Fastly CDN (70+ PoPs) delivers API responses under 100 ms. Paired with SSR/SSG, Contentful provides an enterprise-grade <a href="/en/geo-seo-agency" class="text-rw-blue hover:underline">SEO and GEO</a> foundation.',
    seoLimitations:
      '<strong class="text-secondary dark:text-accent">Contentful provides zero native SEO features</strong>: no sitemap, no automatic meta tags, no 301 redirects. CSR leaves Googlebot with empty pages. Unprotected preview environments get indexed by Google, creating <a href="/en/geo-seo-agency" class="text-rw-blue hover:underline">crawl budget</a> waste and duplicate content against production.',
    geoAngle:
      'According to Rankwell, Contentful\\\'s typed content model (references, rich text, media) can feed schema.org markup directly through the frontend. But this AI citability remains latent until the SSR/SSG layer transforms content types into self-contained factual passages extractable by LLMs.',
  },

  // ============================================
  // QUOTE: Nuclear phrase from the referentiel
  // ============================================
  quote: {
    text: 'According to Rankwell, structured data plays a dual role: it feeds Google\\\'s enriched results (rich snippets, FAQ, reviews) and provides LLMs with an explicit semantic comprehension layer that facilitates factual extraction. A properly marked-up DefinedTerm type becomes an entity directly ingestible by an AI engine.',
    glossarySlug: 'donnees-structurees',
    glossaryLabel: 'Learn more about structured data',
  },

  // ============================================
  // BLOC 3: Common technical problems (TableauService)
  // ============================================
  technicalTable: {
    title: 'Common Contentful SEO problems and solutions',
    interpretation:
      'These problems are specific to Contentful\\\'s headless architecture. Each one degrades Google rankings and reduces the ability of AI engines to extract reliable data from your pages. A technical audit identifies which ones apply to your setup and prioritizes the fixes.',
    columns: ['Problem', 'SEO Impact', 'Rankwell Solution'],
    rows: [
      [
        'Frontend in pure CSR (React SPA without SSR)',
        'Googlebot sees empty pages, zero content in the index',
        'Migration to Next.js (SSR/SSG) or Gatsby (SSG), pre-rendering for bots if migration is not feasible',
      ],
      [
        'No XML sitemap generated by Contentful',
        'Incomplete page discovery, inefficient crawling',
        'Automatic sitemap generation via the frontend (next-sitemap, gatsby-plugin-sitemap) fed by the Content Delivery API',
      ],
      [
        'Meta tags missing or not validated by editors',
        'Duplicate titles, empty descriptions, CTR loss',
        'Creation of mandatory SEO fields in each content type (seoTitle, seoDescription, seoImage) with Contentful validation rules',
      ],
      [
        '301 redirects not handled natively',
        '404 errors on URL changes, PageRank loss',
        'Dedicated "Redirect" content type in Contentful plus redirect middleware on the frontend or CDN rules (Fastly, Vercel)',
      ],
      [
        'Preview environments indexed by Google',
        'Duplicate content between production and staging, authority dilution',
        'Noindex plus authentication on preview environments, separate robots.txt per environment, canonical tags pointing to production',
      ],
      [
        'No schema.org despite a rich content model',
        'No rich snippets, invisible to LLMs',
        'Systematic mapping of content types to schema.org types (Article, Product, FAQPage) via the frontend, JSON-LD injection in the head',
      ],
    ],
  },

  // ============================================
  // BLOC 4: Methodology (StepsDimensions format)
  // ============================================
  methodology: {
    title: 'Our SEO & GEO methodology for Contentful',
    subtitle: 'A structured 8-step approach to Contentful SEO, designed around the platform-specific challenges of enterprise headless CMS architecture.',
    steps: [
      {
        title: 'Contentful technical audit',
        subtitle: 'Full analysis of your headless architecture: content model, environment configuration, frontend rendering layer, and Core Web Vitals.',
        items: [
          'Inventory of content types and their SEO fields (seoTitle, seoDescription, alt text)',
          'Verification of the frontend rendering mode (SSR, SSG, CSR) and Googlebot indexability',
          'Core Web Vitals measurement (LCP, INP, CLS) on key pages',
          'Audit of Contentful environments: preview, staging, production (cross-indexation risks)',
        ],
      },
      {
        title: 'GEO audit: AI citability and presence',
        subtitle: 'Evaluation of your Contentful site visibility across AI engines (ChatGPT, Perplexity, Gemini) using Rankwell\\\'s proprietary GEO audit.',
        items: [
          'Testing 20 to 30 queries related to your business on LLMs',
          'GEO Score calculation across 3 dimensions: Informational Universe, Legitimacy, Factual Density',
          'Benchmark against 3 to 5 direct competitors',
          'Identification of content cited vs ignored by AI engines',
        ],
      },
      {
        title: 'Content model restructuring',
        subtitle: 'Redesign of Contentful content types to integrate mandatory SEO fields and inter-content references for automated internal linking.',
        items: [
          'Addition of mandatory SEO fields on every content type (title, description, OG image, slug)',
          'Creation of dedicated content types: Redirect (301), FAQ, Author (E-E-A-T)',
          'Setup of references between content types for automated internal linking',
          'Configuration of Contentful validations (meta title length, mandatory meta description)',
        ],
      },
      {
        title: 'SSR/SSG frontend optimization',
        subtitle: 'Configuration of the frontend framework (Next.js, Gatsby, Nuxt) to ensure indexability and performance.',
        items: [
          'SSR or SSG rendering setup with incremental static regeneration (ISR on Next.js)',
          'Automatic XML sitemap generation via the Content Delivery API',
          '301 redirect configuration via frontend middleware or CDN rules',
          'Image optimization via the Contentful Images API (WebP format, automatic resizing)',
        ],
      },
      {
        title: 'Schema.org and structured data markup',
        subtitle: 'Systematic mapping of Contentful content types to schema.org types to maximize rich snippets and AI citability.',
        items: [
          'WebSite, Organization, BreadcrumbList markup injected as JSON-LD in the main layout',
          'Article, Product, FAQPage, HowTo mapping on corresponding content types',
          'Dynamic JSON-LD generation from Contentful fields via the frontend',
          'Validation testing with Google Rich Results Test',
        ],
      },
      {
        title: 'Contentful content strategy',
        subtitle: 'Creation of structured content leveraged by the content model for Google rankings and AI citability.',
        items: [
          'Pillar pages plus satellite articles organized via Contentful references',
          'Automated internal linking through reference fields between content types',
          'Thematic FAQ created as a dedicated content type, reusable across multiple pages',
          'Self-contained factual passages designed for LLM extraction',
        ],
      },
      {
        title: 'Authority and link building',
        subtitle: 'Domain authority development through backlinks from specialized headless CMS and enterprise tech sources.',
        items: [
          'Backlinks from headless CMS tech blogs, SaaS publications, and enterprise comparators',
          'Guest posts on high-authority sites within the Contentful and JAMstack ecosystem',
          'Brand mentions in headless CMS comparison articles and architecture guides',
          'Each external mention strengthens PageRank and AI citability',
        ],
      },
      {
        title: 'Tracking, reporting, and iterations',
        subtitle: 'Monthly reporting covering Google rankings, organic traffic, GEO Score, and corrective actions.',
        items: [
          'Google rankings by keyword and by page',
          'Organic traffic segmented by Contentful content type',
          'GEO Score: visibility across AI engines',
          'Core Web Vitals tracking and frontend indexability monitoring',
        ],
      },
    ],
  },

  // ============================================
  // BLOC 5: Deliverables (FeaturesGrid 3x3)
  // ============================================
  features: {
    title: 'The concrete deliverables you receive',
    subtitle: 'Each deliverable is a document or tool usable by your technical team, your Contentful editors, or your management.',
    items: [
      {
        id: 1,
        title: 'Contentful technical audit report',
        description: 'Full diagnostic of your headless architecture: content model (missing SEO fields, absent validations), frontend rendering mode (SSR/SSG/CSR), Core Web Vitals, cross-indexation risks between environments, with a prioritized list of corrective actions.',
      },
      {
        id: 2,
        title: 'GEO audit report',
        description: 'Citability tests of your site and brand in ChatGPT, Perplexity, and Gemini on your target queries. Competitive benchmark and detailed GEO Score out of 100 (Informational Universe, Legitimacy, Factual Density).',
      },
      {
        id: 3,
        title: 'Contentful schema.org kit',
        description: 'Complete mapping of Contentful content types to schema.org types (Article, Product, FAQPage, BreadcrumbList). Frontend code (Next.js or Gatsby) for dynamic JSON-LD generation from Contentful fields.',
      },
      {
        id: 4,
        title: 'Content production and integration',
        description: 'Writing of pages and FAQ optimized for SEO and GEO. Direct integration into Contentful content types via the web interface or the Content Management API. Creation of dedicated content types if needed.',
      },
      {
        id: 5,
        title: 'Link building management and tracking',
        description: 'Backlink acquisition from headless CMS tech blogs, enterprise SaaS comparators, and specialized JAMstack media. Ongoing tracking of acquired links and Domain Rating progression.',
      },
      {
        id: 6,
        title: 'Monthly SEO and GEO report',
        description: 'Google rankings tracked by page and keyword, organic traffic segmented by content type, GEO Score evolution, frontend technical health (indexability, Core Web Vitals), and adjustment recommendations.',
      },
    ],
  },

  // ============================================
  // BLOC 6: AI Visibility (GeoVisibilitySection)
  // ============================================
  geoVisibility: {
    title: 'AI visibility: your Contentful site in ChatGPT, Perplexity, and Google AI',
    intro:
      'When a prospect asks ChatGPT "which SEO agency for a Contentful site?", the LLM compiles web sources to formulate its answer. If your site does not appear in any cited source, it is invisible in this growing acquisition channel.',
    llmBehavior:
      '<h4>Agency recommendation queries</h4><p>On "which SEO agency for a Contentful site?", the LLM does not name any specific agency. It provides a list of 5 to 7 selection criteria (headless CMS experience, content modeling mastery, ability to configure SSR/SSG frontends, enterprise references) and directs toward the Contentful partner page or directories like Sortlist and Clutch. The agency that publishes a detailed methodology with measurable results on Contentful has the potential to be cited.</p><h4>Technical queries</h4><p>On "how to improve SEO on a Contentful site", the LLM generates a structured guide covering 8 to 10 points: content modeling for SEO, SSR/SSG rendering, sitemap generation, redirect management, and Core Web Vitals. It emphasizes the dependency on the frontend framework. Preferred sources are contentful.com/blog, Hygraph documentation, and headless CMS tech blogs. No agency is cited.</p><h4>CMS comparison queries</h4><p>On "Contentful vs Strapi for SEO", the LLM produces a comparison table with 6 to 8 criteria. Contentful is presented as more mature and scalable (Fastly CDN, managed infrastructure, extensive marketplace) but more expensive. Strapi is positioned as open source and more flexible for developers. Sites publishing structured comparisons with measurable criteria are favored as extraction sources.</p><h4>Problem queries</h4><p>On "common Contentful SEO problems", the LLM lists 5 to 7 issues specific to headless architecture: CSR rendering not indexed, no native sitemap, unvalidated meta tags, unmanaged redirects, preview environments exposed to Google. Content structured as problem-solution tables has the highest chance of being extracted.</p>',
    structuredData:
      'For a Contentful site, the recommended schema.org types are: <code>WebSite</code> (primary type), <code>Organization</code> (publishing entity), <code>BreadcrumbList</code> (navigation), <code>FAQPage</code> (FAQ pages), <code>Article</code> or <code>BlogPosting</code> (editorial content), <code>Product</code> (product pages if applicable). The Contentful-specific requirement is that all markup must be generated dynamically on the frontend from content model fields, via a JSON-LD component injected in the head. No native plugin handles schema.org.',
    geoScore:
      'The <strong>Rankwell GEO Score</strong> measures the citability of your Contentful site by AI engines on a scale of 0 to 100. It evaluates three dimensions: Informational Universe (presence and depth of structured content in the content model), Legitimacy and Citability (external trust signals, backlinks, mentions in the headless ecosystem), and Factual Density (richness of schema.org markup generated by the frontend and named entities across pages).',
    glossaryLinks: [
      { label: 'What is GEO?', href: '/en/glossary/geo' },
      { label: 'GEO audit: full methodology', href: '/en/glossary/audit-geo' },
    ],
  },

  // ============================================
  // BLOC 7: FAQ (plain text, no HTML)
  // ============================================
  faq: {
    title: 'Frequently asked questions: Contentful SEO',
    items: [
      {
        question: 'How much does Contentful SEO cost?',
        answer:
          'The SEO budget for a Contentful site is typically higher than for a traditional CMS because it includes frontend SSR/SSG optimization alongside content work. At Rankwell, Contentful SEO engagements start from $2,500/month for a brochure site with fewer than 100 pages, and range from $5,000 to $10,000/month for multi-locale architectures with dozens of content types. This budget covers the content model audit, frontend configuration, content strategy, and GEO monitoring.',
      },
      {
        question: 'How long does it take to see SEO results on Contentful?',
        answer:
          'Initial results appear within 2 to 4 months for technical fixes (switching to SSR/SSG, adding meta tags, generating the sitemap). Ranking improvements on competitive keywords require 4 to 8 months of sustained work. Content model restructuring produces measurable effects as soon as Google recrawls the corrected pages. Rankwell provides a forecast timeline based on the initial audit of your Contentful architecture.',
      },
      {
        question: 'Should I use Next.js or Gatsby as the frontend for Contentful SEO?',
        answer:
          'Next.js and Gatsby are the two most common frontend frameworks paired with Contentful. Next.js offers SSR (Server-Side Rendering) and ISR (Incremental Static Regeneration), suited for sites with frequently updated content. Gatsby generates ultra-fast static pages, ideal for brochure sites and blogs. Rankwell recommends Next.js for enterprise multi-locale projects and Gatsby for stable-content sites. The choice depends on publishing frequency and page count.',
      },
      {
        question: 'How do I fix performance issues on a Contentful site?',
        answer:
          'Performance problems on Contentful rarely come from the CMS itself (the Fastly CDN responds in under 100 ms) but from the frontend. Common causes include an oversized JavaScript bundle, unoptimized images (not using the Contentful Images API), and cascading API calls instead of batched requests. Rankwell audits the frontend, optimizes tree-shaking, activates the Contentful Images API (WebP format, resizing), and configures API response caching.',
      },
      {
        question: 'How can I get my Contentful site cited by ChatGPT and Perplexity?',
        answer:
          'For AI engines to cite your Contentful site, three conditions must be met: content rich in structured factual data within the content model (numbers, definitions, comparisons), schema.org markup dynamically generated from content types (WebSite, Organization, FAQPage, Article), and brand mentions on third-party tech and enterprise sources. The Rankwell GEO Score measures these three dimensions and identifies priority levers.',
      },
      {
        question: 'Is Contentful a good choice for SEO in 2026?',
        answer:
          'Contentful offers excellent SEO potential when the architecture is correctly implemented (SSR/SSG, sitemap, schema.org). Its structured content modeling simplifies structured data production and automated internal linking. However, the complete absence of native SEO requires a technical team capable of configuring the frontend. For businesses without developers, a traditional CMS like WordPress remains more accessible. Rankwell adapts its SEO and GEO methodology to each headless architecture.',
      },
      {
        question: 'Why choose Rankwell for Contentful SEO?',
        answer:
          'Rankwell combines headless technical SEO expertise (content model audit, SSR/SSG frontend configuration, schema.org mapping from content types) with the GEO dimension that the vast majority of SEO agencies do not offer. Our 8-step methodology covers the challenges specific to Contentful: absence of native SEO, frontend dependency, content modeling, environment management. The proprietary GEO Score measures your site visibility across AI engines.',
      },
    ],
  },

  // ============================================
  // CTA + Internal linking
  // ============================================
  cta: {
    title: 'Ready to optimize your Contentful site?',
    description:
      'Request a free GEO & SEO audit of your Contentful site. Our SEO & GEO consultants analyze your content model, your frontend rendering layer, and your AI engine visibility, and deliver a concrete action plan.',
    buttonText: 'Request a free audit',
    buttonHref: '/en/contact',
    relatedPages: {
      secteurs: [
        { label: 'SEO for SaaS', href: '/en/geo-seo-agency/sector/saas' },
        { label: 'SEO for Fintech', href: '/en/geo-seo-agency/sector/fintech' },
        { label: 'SEO for E-commerce', href: '/en/geo-seo-agency/sector/ecommerce' },
      ],
      projets: [
        { label: 'Website Redesign SEO', href: '/en/geo-seo-agency/project/refonte' },
        { label: 'Website Creation SEO', href: '/en/geo-seo-agency/project/creation-site' },
        { label: 'International SEO', href: '/en/geo-seo-agency/project/international' },
      ],
      cms: [
        { label: 'Strapi SEO', href: '/en/geo-seo-agency/cms/strapi' },
        { label: 'Prismic SEO', href: '/en/geo-seo-agency/cms/prismic' },
        { label: 'Next.js SEO', href: '/en/geo-seo-agency/cms/nextjs' },
      ],
      glossaire: [
        { label: 'Structured Data (Schema.org)', href: '/en/glossary/donnees-structurees' },
        { label: 'Technical SEO', href: '/en/glossary/seo-technique' },
        { label: 'Crawl Budget', href: '/en/glossary/crawl-budget' },
      ],
    },
  },

  // Related CMS links
  relatedSectors: {
    title: 'SEO & GEO by CMS and platform',
    items: [
      { label: 'Strapi', href: '/en/geo-seo-agency/cms/strapi' },
      { label: 'Prismic', href: '/en/geo-seo-agency/cms/prismic' },
      { label: 'Next.js', href: '/en/geo-seo-agency/cms/nextjs' },
      { label: 'Gatsby', href: '/en/geo-seo-agency/cms/gatsby' },
      { label: 'Nuxt.js', href: '/en/geo-seo-agency/cms/nuxtjs' },
      { label: 'WordPress', href: '/en/geo-seo-agency/cms/wordpress' },
    ],
  },
};

export default data;
