/**
 * DATA: CMS Next.js Page (EN)
 * Route: /en/geo-seo-agency/cms/nextjs
 *
 * English version adapted for the international Next.js market.
 * Content based on LLM auto-test (March 2026) and global Next.js ecosystem.
 */

import type { CmsPageData } from '@/types/sector-pages';

const data: CmsPageData = {
  // ============================================
  // SEO
  // ============================================
  seo: {
    slug: 'nextjs',
    title: 'Next.js SEO & GEO Agency - Rankwell',
    description:
      'Rankwell optimizes SEO and AI visibility (GEO) for Next.js websites. SSR, SSG, Metadata API, generateStaticParams, schema.org: a complete methodology built for Next.js.',
  },

  // ============================================
  // BLOC 1: HERO
  // ============================================
  hero: {
    breadcrumb: [
      { label: 'Home', href: '/' },
      { label: 'GEO & SEO Agency', href: '/en/geo-seo-agency' },
      { label: 'CMS & Platforms', href: '/en/geo-seo-agency/sectors' },
      { label: 'Next.js' },
    ],
    title: 'Next.js SEO & GEO: Rankings and AI Visibility',
    subtitle:
      'Client-side rendering blocking indexation, metadata scattered across the codebase, no built-in CMS for content management: SEO on a Next.js site demands dual expertise in technical SEO and React development. Our experts combine technical SEO and GEO to rank your site on Google and get your brand cited by AI engines.',
    ctaText: 'Request a Next.js SEO & GEO audit',
    ctaHref: '/en/contact',
  },

  // ============================================
  // BLOC 2: Why SEO is different on Next.js (IntroService)
  // ============================================
  whyDifferent: {
    title: 'Why SEO is different on Next.js',
    seoStrengths:
      '<strong class="text-secondary dark:text-accent">Next.js powers over 1.1 million production websites</strong> (Vercel, TikTok, Notion). Three native rendering modes (SSR, SSG, ISR) serve complete HTML to crawlers. The Metadata API and <code>generateStaticParams</code> enable a programmatic <a href="/en/geo-seo-agency" class="text-rw-blue hover:underline">SEO and GEO</a> strategy at scale.',
    seoLimitations:
      '<strong class="text-secondary dark:text-accent">A client-side rendered React component stays invisible to Googlebot for 5 to 10 seconds</strong>. No built-in CMS means content requires a headless CMS (Strapi, Contentful), and schema.org markup needs custom JSON-LD code with no graphical interface.',
    geoAngle:
      'According to Rankwell, Next.js server-rendered HTML is immediately readable by GPTBot and ClaudeBot, and JSON-LD injected in the source code provides reliable structured data. This advantage only materializes when critical components use SSR and factual passages are structured for extraction.',
  },

  // ============================================
  // QUOTE: Nuclear phrase from the referentiel
  // ============================================
  quote: {
    text: 'According to Rankwell, technical SEO in 2026 carries a dual challenge: ensuring site accessibility for traditional indexing robots (Googlebot, Bingbot) and for AI engine robots (GPTBot, ClaudeBot, PerplexityBot), because these two families of crawlers behave differently and their robots.txt directives must be managed separately.',
    glossarySlug: 'seo-technique',
    glossaryLabel: 'Learn more about technical SEO',
  },

  // ============================================
  // BLOC 3: Common technical problems (TableauService)
  // ============================================
  technicalTable: {
    title: 'Common Next.js SEO problems and solutions',
    interpretation:
      'These problems affect the majority of Next.js sites whose architecture was not designed with SEO in mind. A technical audit identifies which ones impact your site and prioritizes fixes based on their effect on Google rankings and AI citability.',
    columns: ['Problem', 'SEO Impact', 'Rankwell Solution'],
    rows: [
      [
        'Components rendered client-side (CSR) instead of server-side',
        'Content invisible to Googlebot and AI crawlers until JavaScript executes',
        'Component-by-component audit: migration to App Router Server Components (RSC) for all indexable content',
      ],
      [
        'Missing or duplicate metadata on dynamic pages',
        'Identical titles and descriptions across hundreds of pages generated by generateStaticParams',
        'Metadata API setup with dynamic generateMetadata() and title templates per route segment',
      ],
      [
        '/_next/ directory crawled by bots',
        'Crawl budget wasted on static JS/CSS/image files',
        'Block /_next/ in robots.txt, verify SSR does not depend on these URLs for rendering',
      ],
      [
        'No schema.org markup (no native plugin)',
        'No rich snippets, unstructured data for LLMs',
        'JSON-LD injection in layouts and pages via dedicated React components (WebSite, Organization, BreadcrumbList, FAQPage)',
      ],
      [
        'Slow hydration on heavy pages (Suspense, streaming)',
        'LCP > 3s on mobile, CLS caused by progressive component loading',
        'Split heavy components with dynamic() and loading.tsx, preload critical data in the server layout',
      ],
      [
        'Misconfigured headless CMS (Strapi, Contentful, Prismic)',
        'Content not revalidated after publication, stale cached pages',
        'ISR (Incremental Static Regeneration) configuration with webhook-triggered revalidation from the headless CMS',
      ],
    ],
  },

  // ============================================
  // BLOC 4: Methodology (StepsDimensions format)
  // ============================================
  methodology: {
    title: 'Our SEO & GEO methodology for Next.js',
    subtitle: 'A structured 8-step approach designed around the technical specifics of Next.js and the React ecosystem.',
    steps: [
      {
        title: 'Next.js technical audit',
        subtitle: 'Analysis of the Next.js architecture: rendering mode per page (SSR, SSG, CSR, ISR), App Router configuration, and Core Web Vitals.',
        items: [
          'Page-by-page mapping of rendering modes (Server Components vs Client Components)',
          'Core Web Vitals measurement (LCP, INP, CLS) on mobile and desktop via Lighthouse CI',
          'Crawl budget analysis: indexed pages vs wasted /_next/ URLs in server logs',
          'Headless CMS configuration check (Strapi, Contentful, Prismic) and revalidation pipeline review',
        ],
      },
      {
        title: 'GEO audit: AI citability and presence',
        subtitle: 'Evaluation of your Next.js site visibility across AI engines (ChatGPT, Perplexity, Gemini) using Rankwell\'s proprietary GEO audit.',
        items: [
          'Testing 20 to 30 queries related to your business on LLMs',
          'GEO Score calculation across 3 dimensions: Informational Universe, Legitimacy, Factual Density',
          'Benchmark against 3 to 5 direct competitors',
          'Verification that server-rendered HTML is accessible to GPTBot and ClaudeBot (not blocked by robots.txt)',
        ],
      },
      {
        title: 'Rendering architecture rationalization',
        subtitle: 'Migration of critical components from CSR to SSR/SSG to guarantee content indexability by Google and AI crawlers.',
        items: [
          'Identification of Client Components that should be Server Components',
          'generateStaticParams configuration for static generation of high-volume pages',
          'ISR setup with webhook-triggered revalidation for dynamic content',
          'Dead JavaScript removal and unused npm dependency cleanup (tree shaking, bundle analysis)',
        ],
      },
      {
        title: 'Performance optimization',
        subtitle: 'Core Web Vitals improvement using native Next.js tools: next/image, next/font, next/script.',
        items: [
          'Image conversion via next/image (automatic WebP, lazy loading, responsive sizing)',
          'Font loading via next/font to eliminate FOUT (Flash of Unstyled Text)',
          'next/script configuration with strategy="lazyOnload" for non-critical third-party scripts',
          'Deployment on Vercel or edge CDN to serve pages from the nearest point of presence',
        ],
      },
      {
        title: 'Advanced SEO configuration',
        subtitle: 'Full setup of the Metadata API, dynamic sitemap, and schema.org markup via dedicated React components.',
        items: [
          'Metadata API: dynamic generateMetadata() per page with title template per segment',
          'Dynamic XML sitemap via app/sitemap.ts with exclusion of technical routes',
          'robots.txt configured in app/robots.ts: block /_next/, fine-grained GPTBot and ClaudeBot management',
          'Schema.org markup: JSON-LD components for WebSite, Organization, BreadcrumbList, FAQPage, Article',
        ],
      },
      {
        title: 'Content strategy for Next.js',
        subtitle: 'Production of content structured for Google rankings and AI citability, integrated via the headless CMS.',
        items: [
          'Pillar pages + satellite articles organized in topical clusters within the headless CMS',
          'Contextual internal linking between pages generated by generateStaticParams',
          'Thematic FAQ sections structured as JSON-LD FAQPage for LLM extraction',
          'Self-contained factual passages embedded in each page (definitions, data points, comparisons)',
        ],
      },
      {
        title: 'Authority and link building',
        subtitle: 'Domain authority development through backlinks from specialized tech sites and brand mentions exploitable by LLMs.',
        items: [
          'Backlinks from tech blogs, React/JavaScript publications, and framework comparators',
          'Guest posts on high-authority thematic websites (web development, SaaS)',
          'Brand mentions in comparison articles and technical case studies',
          'Each external mention strengthens Domain Rating and AI citability',
        ],
      },
      {
        title: 'Tracking, reporting, and iterations',
        subtitle: 'Monthly reporting covering Google rankings, organic traffic, GEO Score, and technical health of the Next.js site.',
        items: [
          'Google rankings by keyword and by page (tracking SSR vs SSG pages)',
          'Organic traffic segmented by content type and rendering source',
          'GEO Score: visibility across AI engines (ChatGPT, Perplexity, Gemini)',
          'Core Web Vitals evolution and indexation error monitoring in Search Console',
        ],
      },
    ],
  },

  // ============================================
  // BLOC 5: Deliverables (FeaturesGrid 3x3)
  // ============================================
  features: {
    title: 'The concrete deliverables you receive',
    subtitle: 'Each deliverable is a document or tool usable by your React developers, your product team, or your management.',
    items: [
      {
        id: 1,
        title: 'Next.js technical audit report',
        description: 'Full diagnostic of your Next.js architecture: SSR/SSG/CSR mapping per page, Core Web Vitals, JavaScript bundle analysis, headless CMS configuration, with a prioritized list of corrective actions.',
      },
      {
        id: 2,
        title: 'GEO audit report',
        description: 'Citability tests of your site and brand in ChatGPT, Perplexity, and Gemini on your target queries. Competitive benchmark and detailed GEO Score out of 100 (Informational Universe, Legitimacy, Factual Density).',
      },
      {
        id: 3,
        title: 'Next.js schema.org kit',
        description: 'Ready-to-integrate React JSON-LD components for the App Router: WebSite, Organization, BreadcrumbList, FAQPage, Article, and business-specific types. Documented TypeScript code with integration instructions for your developers.',
      },
      {
        id: 4,
        title: 'Content production and integration',
        description: 'Writing of pages and articles optimized for SEO and GEO. Integration into your headless CMS (Strapi, Contentful, Prismic) or directly into the project MDX files.',
      },
      {
        id: 5,
        title: 'Link building management and tracking',
        description: 'Backlink acquisition from tech blogs, React/JavaScript publications, framework comparators, and SaaS-focused media. Ongoing tracking of acquired links and Domain Rating progression.',
      },
      {
        id: 6,
        title: 'Monthly SEO and GEO report',
        description: 'Google rankings tracked by page and keyword, organic traffic segmented by rendering mode (SSR/SSG), GEO Score evolution, Core Web Vitals, and technical adjustment recommendations.',
      },
    ],
  },

  // ============================================
  // BLOC 6: AI Visibility (GeoVisibilitySection)
  // ============================================
  geoVisibility: {
    title: 'AI visibility: your Next.js site in ChatGPT, Perplexity, and Google AI',
    intro:
      'When a prospect asks ChatGPT "which SEO agency should I choose for a Next.js site?", the LLM compiles web sources to formulate its answer. If your site does not appear in any cited source, it is invisible in this new acquisition channel.',
    llmBehavior:
      '<h4>Agency recommendation queries</h4><p>On "which SEO agency for a Next.js site?", the LLM does not cite any agency by name for combined Next.js + SEO expertise. It lists selection criteria (SSR mastery, React experience, Metadata API configuration) and points toward development agency directories like DesignRush, Clutch, and Pagepro rankings. Next.js development agencies (FocusReactive, Naturaily) are sometimes mentioned, but never for their SEO expertise. The agency that combines Next.js technical expertise with a documented SEO methodology has the potential to be cited first.</p><h4>Technical queries</h4><p>On "how to improve SEO on a Next.js website", the LLM generates a structured guide covering 6 to 8 points: rendering strategies (SSR, SSG, ISR), Metadata API, next/image component, JSON-LD structured data, Core Web Vitals, and monitoring tools. The preferred sources are the official Next.js documentation, the Vercel SEO Playbook, Strapi Blog, and Prismic Blog. The content is heavily developer-oriented. No SEO agency is cited.</p><h4>CMS comparison queries</h4><p>On "Next.js vs WordPress for SEO", the LLM produces a comparison of 5 to 6 criteria: performance, rendering control, plugin ecosystem, costs, and maintenance. Next.js is presented as superior in performance and HTML control, but more demanding in technical skills. Sites publishing comparisons with measured data (Core Web Vitals, TTFB, Lighthouse scores) are favored as extraction sources.</p><h4>Technical problem queries</h4><p>On "common Next.js SEO problems", the LLM lists 6 to 8 issues: client-side rendered content not indexed, duplicate metadata, /_next/ directory crawled, missing schema.org, slow hydration, and Suspense/streaming challenges. Sources include the official documentation, FocusReactive blog, Medium articles, and GitHub discussions (vercel/next.js). Content structured as problem-solution tables is favored for extraction.</p>',
    structuredData:
      'For a Next.js site, the recommended schema.org types are: <code>WebSite</code> (primary type), <code>Organization</code> or <code>LocalBusiness</code> (depending on the business), <code>BreadcrumbList</code> (navigation), <code>FAQPage</code> (FAQ pages), <code>Article</code> or <code>BlogPosting</code> (editorial content). Next.js has no built-in SEO plugin: markup is implemented via React components that inject JSON-LD into the <code>&lt;head&gt;</code> of each page. The <code>next-seo</code> library simplifies this injection, but the native App Router Metadata API (Next.js 14+) offers a dependency-free alternative.',
    geoScore:
      'The <strong>Rankwell GEO Score</strong> measures the citability of your Next.js site by AI engines on a scale of 0 to 100. It evaluates three dimensions: Informational Universe (presence and depth of server-rendered content), Legitimacy and Citability (external trust signals, backlinks from tech sources, mentions in React/JavaScript publications), and Factual Density (richness of JSON-LD markup injected in the source code and named entities across pages).',
    glossaryLinks: [
      { label: 'What is GEO?', href: '/en/glossary/geo' },
      { label: 'GEO audit: full methodology', href: '/en/glossary/audit-geo' },
    ],
  },

  // ============================================
  // BLOC 7: FAQ (plain text, no HTML)
  // ============================================
  faq: {
    title: 'Frequently asked questions: Next.js SEO',
    items: [
      {
        question: 'How much does Next.js SEO cost?',
        answer:
          'The SEO budget for a Next.js site depends on the architecture complexity (number of pages generated by generateStaticParams, headless CMS configuration, rendering modes used). At Rankwell, Next.js SEO engagements start from $2,000/month for a site under 100 pages, and range from $4,000 to $8,000/month for applications with thousands of dynamic pages (headless e-commerce, marketplace, SaaS). This budget covers the technical audit, rendering architecture optimization, content strategy, and GEO monitoring.',
      },
      {
        question: 'How long does it take to see SEO results on Next.js?',
        answer:
          'Technical fixes (CSR to SSR migration, Metadata API configuration, robots.txt optimization) produce measurable effects within the first month in Search Console. Ranking on competitive keywords requires 4 to 8 months of sustained work on content and link building. The advantage of Next.js is that performance optimizations (next/image, next/font, ISR) improve Core Web Vitals quickly. Rankwell provides a forecast timeline based on the initial audit of your architecture.',
      },
      {
        question: 'Should I use next-seo or the native Next.js Metadata API?',
        answer:
          'Both approaches are valid. The native App Router Metadata API (Next.js 14+) handles title, description, and Open Graph tags without external dependencies, with generateMetadata() for dynamic pages. The next-seo library adds ready-to-use JSON-LD components (FAQPage, Article, Product) and simplifies schema.org management. Rankwell recommends the native Metadata API for base metadata and next-seo (or custom JSON-LD components) for advanced structured data.',
      },
      {
        question: 'How do I fix indexation problems caused by JavaScript rendering?',
        answer:
          'The main problem is client-side rendering (CSR): components marked "use client" are not rendered in the initial HTML sent to Googlebot. Rankwell audits each page to identify components that should use server rendering (Server Components). Migrating to App Router RSC guarantees that indexable content is present in the HTML source. For interactive components, we use the "progressive enhancement" pattern: static content via SSR, interactivity via CSR.',
      },
      {
        question: 'How can I get my Next.js site cited by ChatGPT and Perplexity?',
        answer:
          'AI engines cite sites whose content is accessible without JavaScript execution (server-rendered HTML), rich in verifiable factual data, and structured with JSON-LD. Next.js offers a native advantage through SSR, but factual passages must be explicit and AI crawlers (GPTBot, ClaudeBot) must not be blocked by robots.txt. The Rankwell GEO Score measures these three dimensions and identifies the priority levers to increase your site citability.',
      },
      {
        question: 'Is Next.js the best framework for SEO in 2026?',
        answer:
          'Next.js is the highest-performing React framework for SEO in 2026, thanks to its three native rendering modes (SSR, SSG, ISR), its built-in Metadata API, and its performance optimizations (next/image, next/font). Nuxt.js offers a similar advantage in the Vue.js ecosystem. WordPress remains more accessible for editorial sites without a development team. The choice depends on your technical resources: Next.js requires a React team. Rankwell adapts its SEO and GEO methodology to the specifics of each tech stack.',
      },
      {
        question: 'Why choose Rankwell for Next.js SEO?',
        answer:
          'Rankwell combines Next.js technical SEO expertise (SSR/SSG architecture auditing, Metadata API configuration, JSON-LD components, Core Web Vitals optimization) with the GEO dimension that 93% of SEO agencies have not yet integrated. Our 8-step methodology covers Next.js-specific challenges: client-side rendering not indexed, misconfigured headless CMS, missing schema.org, /_next/ directory crawled by bots. The proprietary GEO Score measures your site visibility across AI engines.',
      },
    ],
  },

  // ============================================
  // CTA + Internal linking
  // ============================================
  cta: {
    title: 'Ready to optimize your Next.js site?',
    description:
      'Request a free GEO & SEO audit of your Next.js site. Our SEO & GEO consultants analyze your rendering architecture, Metadata API configuration, Core Web Vitals, and AI engine visibility, and deliver a concrete action plan.',
    buttonText: 'Request a free audit',
    buttonHref: '/en/contact',
    relatedPages: {
      secteurs: [
        { label: 'SEO for SaaS', href: '/en/geo-seo-agency/sector/saas' },
        { label: 'SEO for Startups', href: '/en/geo-seo-agency/sector/startup' },
        { label: 'SEO for E-commerce', href: '/en/geo-seo-agency/sector/ecommerce' },
      ],
      projets: [
        { label: 'SEO for Business Websites', href: '/en/geo-seo-agency/project/site-vitrine' },
        { label: 'Website Redesign SEO', href: '/en/geo-seo-agency/project/refonte' },
        { label: 'New Website SEO', href: '/en/geo-seo-agency/project/creation-site' },
      ],
      cms: [
        { label: 'Nuxt.js SEO', href: '/en/geo-seo-agency/cms/nuxtjs' },
        { label: 'Gatsby SEO', href: '/en/geo-seo-agency/cms/gatsby' },
        { label: 'Webflow SEO', href: '/en/geo-seo-agency/cms/webflow' },
      ],
      glossaire: [
        { label: 'Technical SEO', href: '/en/glossary/seo-technique' },
        { label: 'Core Web Vitals', href: '/en/glossary/core-web-vitals' },
        { label: 'Structured Data (Schema.org)', href: '/en/glossary/donnees-structurees' },
      ],
    },
  },

  // Related CMS links
  relatedSectors: {
    title: 'SEO & GEO by CMS and platform',
    items: [
      { label: 'Nuxt.js', href: '/en/geo-seo-agency/cms/nuxtjs' },
      { label: 'Gatsby', href: '/en/geo-seo-agency/cms/gatsby' },
      { label: 'Webflow', href: '/en/geo-seo-agency/cms/webflow' },
      { label: 'Strapi', href: '/en/geo-seo-agency/cms/strapi' },
      { label: 'Contentful', href: '/en/geo-seo-agency/cms/contentful' },
    ],
  },
};

export default data;
