/**
 * DATA: CMS Sylius Page (EN)
 * Route: /en/geo-seo-agency/cms/sylius
 *
 * English version adapted for the international Sylius/Symfony e-commerce market.
 * Content based on LLM auto-test (March 2026) and global Sylius ecosystem.
 */

import type { CmsPageData } from '@/types/sector-pages';

const data: CmsPageData = {
  // ============================================
  // SEO
  // ============================================
  seo: {
    slug: 'sylius',
    title: 'Sylius SEO & GEO Agency - Rankwell',
    description:
      'Rankwell optimizes SEO and AI visibility (GEO) for Sylius stores. Symfony technical audit, SEO plugins, schema.org, API-first performance: a complete methodology built for Sylius.',
  },

  // ============================================
  // BLOC 1: HERO
  // ============================================
  hero: {
    breadcrumb: [
      { label: 'Home', href: '/' },
      { label: 'GEO & SEO Agency', href: '/en/geo-seo-agency' },
      { label: 'CMS & Platforms', href: '/en/geo-seo-agency/sectors' },
      { label: 'Sylius' },
    ],
    title: 'Sylius SEO & GEO: Rankings and AI Visibility',
    subtitle:
      'No native SEO management, no built-in XML sitemap, no default schema.org: Sylius offers total freedom but requires every SEO component to be custom-built. Our experts combine Symfony technical SEO and GEO to rank your store on Google and get it cited by AI engines.',
    ctaText: 'Request a Sylius SEO & GEO audit',
    ctaHref: '/en/contact',
  },

  // ============================================
  // BLOC 2: Why SEO is different on Sylius (IntroService)
  // ============================================
  whyDifferent: {
    title: 'Why SEO is different on Sylius',
    seoStrengths:
      '<strong class="text-secondary dark:text-accent">Sylius powers over 7,000 active stores worldwide</strong> with 34% year-over-year growth. Built on Symfony and API Platform, it provides absolute control over HTML, routes, and structured markup. Decoupled SSR via Next.js or Nuxt.js ensures a DOM readable by Googlebot, a strong foundation for an <a href="/en/geo-seo-agency" class="text-rw-blue hover:underline">SEO and GEO</a> strategy.',
    seoLimitations:
      '<strong class="text-secondary dark:text-accent">Sylius provides zero native SEO features</strong>: no meta tags, no XML sitemap, no canonical URLs, no schema.org. Everything must be added via community plugins (Dedi SEO, BetterSEO, Sitemap Plugin) or custom Symfony code. With only <strong>0.04% e-commerce market share</strong>, a <a href="/en/geo-seo-agency" class="text-rw-blue hover:underline">GEO & SEO agency</a> with Symfony expertise is essential.',
    geoAngle:
      'According to Rankwell, Sylius stores hold a structural GEO advantage: API-first architecture allows injecting Product, Offer, and BreadcrumbList markup at the finest granularity. But this potential only materializes if schema.org is implemented and product pages contain factual passages written for LLM extraction.',
  },

  // ============================================
  // QUOTE: Nuclear phrase from the referentiel
  // ============================================
  quote: {
    text: 'According to Rankwell, e-commerce SEO in 2026 integrates an unprecedented challenge: LLMs are becoming a full-fledged product recommendation channel. ChatGPT and Perplexity compare products, recommend brands, and cite product pages in their responses.',
    glossarySlug: 'seo-ecommerce',
    glossaryLabel: 'Learn more about e-commerce SEO',
  },

  // ============================================
  // BLOC 3: Common technical problems (TableauService)
  // ============================================
  technicalTable: {
    title: 'Common Sylius SEO problems and solutions',
    interpretation:
      'Sylius places the responsibility for every SEO component on the developer. These issues affect nearly all unoptimized stores and stem directly from the absence of native SEO features in the framework. A Symfony technical audit identifies which ones apply to your project.',
    columns: ['Problem', 'SEO Impact', 'Rankwell Solution'],
    rows: [
      [
        'No configurable meta tags without a plugin (neither title nor description)',
        'Pages indexed with generic tags, degraded CTR in search results',
        'Installation and configuration of the Dedi SEO or BetterSEO (JoppeDC) plugin to manage meta tags per product, taxon, and CMS page',
      ],
      [
        'No XML sitemap generated by default',
        'Googlebot does not discover new product pages, delayed indexation',
        'Deployment of Stefan Doorn\\\'s Sitemap Plugin with automatic regeneration and submission via Google Search Console',
      ],
      [
        'JavaScript rendering with a decoupled SPA front end (React, Vue)',
        'Content invisible to Googlebot if SSR is absent, empty pages in the index',
        'SSR configuration via Nuxt.js or Next.js, static pre-rendering (SSG) of catalog pages, verification via the GSC URL Inspection tool',
      ],
      [
        'No built-in schema.org (Product, Offer, BreadcrumbList)',
        'No rich snippets (price, reviews, availability), invisibility to LLMs',
        'JSON-LD markup injection via the Dedi plugin (RichSnippets Product + Breadcrumb) or custom Twig/Symfony code for specific types',
      ],
      [
        'Duplicate content between product pages and taxon (category) pages',
        'Crawl budget dilution, cannibalization between product URLs and category URLs',
        'Canonical tag configuration via Symfony routing, noindex on filter pages and non-strategic paginations',
      ],
      [
        '301 redirects not managed through the admin interface',
        'Broken links after URL changes, loss of accumulated PageRank',
        'Redirect system setup via Symfony routing configuration (config/routes.yaml) or dedicated bundle, monthly 404 monitoring',
      ],
    ],
  },

  // ============================================
  // BLOC 4: Methodology (StepsDimensions format)
  // ============================================
  methodology: {
    title: 'Our SEO & GEO methodology for Sylius',
    subtitle: 'A structured 8-step approach to Sylius SEO, designed around the platform-specific challenges of this Symfony-based e-commerce framework.',
    steps: [
      {
        title: 'Sylius technical audit',
        subtitle: 'Full analysis of your Sylius installation: Symfony version, PHP configuration, installed plugins, front-end architecture (monolithic or decoupled), and Core Web Vitals.',
        items: [
          'Inventory of active Sylius plugins (Dedi SEO, BetterSEO, Sitemap, CMS Page)',
          'Core Web Vitals measurement (LCP, INP, CLS) on product and category pages',
          'Crawl budget analysis: indexed pages vs wasted pages (filters, paginations, empty taxons)',
          'SSR/SSG rendering verification if the front end is decoupled (Nuxt.js, Next.js)',
        ],
      },
      {
        title: 'GEO audit: AI citability and presence',
        subtitle: 'Evaluation of your Sylius store visibility across AI engines (ChatGPT, Perplexity, Gemini) using Rankwell\\\'s proprietary GEO audit.',
        items: [
          'Testing 20 to 30 queries related to your products and brand on LLMs',
          'GEO Score calculation across 3 dimensions: Informational Universe, Legitimacy, Factual Density',
          'Benchmark against 3 to 5 direct e-commerce competitors',
          'Identification of product pages cited vs ignored by AI engines',
        ],
      },
      {
        title: 'Building the missing SEO layer',
        subtitle: 'Installation and configuration of essential SEO plugins that Sylius does not provide natively.',
        items: [
          'Deployment of the Dedi SEO plugin (meta tags, OpenGraph, RichSnippets) or BetterSEO depending on context',
          'Sitemap Plugin configuration with exclusion of non-strategic pages',
          'Canonical URL and 301 redirect setup via Symfony routing',
          'robots.txt configuration and X-Robots-Tag directives for non-HTML resources',
        ],
      },
      {
        title: 'Symfony performance optimization',
        subtitle: 'Page speed improvement by leveraging Symfony-specific and Sylius architecture optimization levers.',
        items: [
          'OPcache activation and Redis configuration for HTTP cache and sessions',
          'Doctrine ORM query optimization (lazy loading, efficient pagination)',
          'Product image compression and WebP conversion with lazy loading',
          'CDN setup (Cloudflare, BunnyCDN) and Cache-Control header configuration',
        ],
      },
      {
        title: 'E-commerce schema.org markup',
        subtitle: 'Complete structured data implementation for product pages, categories, and brand pages.',
        items: [
          'Product + Offer markup on every product page (price, availability, reviews)',
          'BreadcrumbList on all pages via the Dedi plugin or custom Twig templates',
          'Organization and WebSite on main pages',
          'FAQPage on content pages and buying guides',
        ],
      },
      {
        title: 'E-commerce content strategy',
        subtitle: 'Creation of structured content for Google rankings and AI citability, integrated via the SyliusCmsPage Plugin by Monsieur Biz.',
        items: [
          'Buying guides and product comparisons organized in semantic clusters',
          'Enriched category (taxon) descriptions with factual technical data',
          'FAQ sections per category inspired by Google PAA, written for LLM extraction',
          'Internal linking between product pages, guides, and category pages',
        ],
      },
      {
        title: 'Authority and e-commerce link building',
        subtitle: 'Domain authority development through backlinks from e-commerce specialized sites and publications in your sector.',
        items: [
          'Backlinks from product comparison sites, e-commerce blogs, and industry media',
          'Guest publications on high-authority sites in your niche',
          'Brand mentions in buying guides and comparison articles',
          'Each external mention strengthens PageRank and AI citability of your product pages',
        ],
      },
      {
        title: 'Tracking, reporting, and iterations',
        subtitle: 'Monthly reporting covering Google rankings, organic traffic, GEO Score, and the technical health of your Sylius installation.',
        items: [
          'Google rankings by keyword and by product/category page',
          'Organic traffic segmented by page type (product, taxon, guide, CMS)',
          'GEO Score: visibility of your products and brand across AI engines',
          'Core Web Vitals evolution and Sylius plugin monitoring (updates, compatibility)',
        ],
      },
    ],
  },

  // ============================================
  // BLOC 5: Deliverables (FeaturesGrid 3x3)
  // ============================================
  features: {
    title: 'The concrete deliverables you receive',
    subtitle: 'Each deliverable is a document or tool usable by your Symfony development team, your e-commerce team, or your management.',
    items: [
      {
        id: 1,
        title: 'Sylius technical audit report',
        description: 'Full diagnostic of your Sylius installation: Symfony and PHP version, active plugins (Dedi SEO, BetterSEO, Sitemap), front-end architecture (monolithic or decoupled SSR/SSG), Core Web Vitals, crawl budget, with a prioritized list of corrective actions.',
      },
      {
        id: 2,
        title: 'GEO audit report',
        description: 'Citability tests of your products and brand in ChatGPT, Perplexity, and Gemini on your target e-commerce queries. Competitive benchmark and detailed GEO Score out of 100 (Informational Universe, Legitimacy, Factual Density).',
      },
      {
        id: 3,
        title: 'Sylius schema.org kit',
        description: 'Product, Offer, AggregateRating, BreadcrumbList, and Organization markup implemented via the Dedi SEO plugin or custom Twig/JSON-LD injection in your Symfony templates. Technical guide with code examples for your development team.',
      },
      {
        id: 4,
        title: 'Content production and integration',
        description: 'Writing of product pages, buying guides, and FAQ sections optimized for SEO and GEO. Direct integration into Sylius via the SyliusCmsPage Plugin by Monsieur Biz or through Twig template access.',
      },
      {
        id: 5,
        title: 'Link building management and tracking',
        description: 'Backlink acquisition from e-commerce comparison sites, specialized blogs, and industry media in your sector. Ongoing tracking of acquired links and Domain Rating progression.',
      },
      {
        id: 6,
        title: 'Monthly SEO and GEO report',
        description: 'Google rankings tracked by product and category page, segmented organic traffic, GEO Score evolution, Sylius technical health (Symfony version, plugins, Core Web Vitals), and adjustment recommendations.',
      },
    ],
  },

  // ============================================
  // BLOC 6: AI Visibility (GeoVisibilitySection)
  // ============================================
  geoVisibility: {
    title: 'AI visibility: your Sylius store in ChatGPT, Perplexity, and Google AI',
    intro:
      'When a buyer asks ChatGPT "what is the best product for [your category]?", the LLM compiles web sources to formulate its answer. If your Sylius product pages lack exploitable structured data, your store is invisible in this new recommendation channel.',
    llmBehavior:
      '<h4>Agency recommendation queries</h4><p>On "which SEO agency for a Sylius site?", the LLM does not cite any agency by name. It explains that Sylius is a niche e-commerce framework (0.04% market share) and recommends looking for an agency combining Symfony expertise and technical SEO. It notes that the Sylius ecosystem is concentrated in France (50% of users) and Poland. The agency that demonstrates documented Sylius technical expertise has the potential to be cited first.</p><h4>Technical queries</h4><p>On "how to improve SEO on a Sylius website?", the LLM generates a guide covering 7 to 9 points, emphasizing the absence of native SEO. It recommends the Dedi SEO and BetterSEO (JoppeDC) plugins, Stefan Doorn\\\'s Sitemap Plugin, and SSR configuration for decoupled front ends. No agency is cited. The preferred sources are the official Sylius documentation, the Sylius Store, and GitHub.</p><h4>CMS comparison queries</h4><p>On "Sylius vs PrestaShop for SEO", the LLM produces a comparison where PrestaShop is presented as more accessible for SEO (native URL rewriting, per-product meta tags, built-in sitemap) while Sylius is positioned as more flexible but requiring SEO to be entirely custom-built. Content publishing structured comparisons with measurable criteria is favored as extraction sources.</p><h4>Technical problem queries</h4><p>On "common Sylius SEO problems", the LLM provides a list of 6 to 8 issues specific to the API-first architecture: no native meta tags, no XML sitemap, no built-in schema.org, unindexed JavaScript rendering, duplicate content between product and taxon pages. Content that structures problem/solution pairs in tables has the highest extraction potential.</p>',
    structuredData:
      'For a Sylius store, the recommended schema.org types are: <code>Product</code> + <code>Offer</code> (product pages with price, availability, reviews), <code>BreadcrumbList</code> (taxon navigation), <code>Organization</code> (homepage), <code>WebSite</code> + <code>SearchAction</code> (internal search), <code>FAQPage</code> (buying guides). The Dedi SEO plugin natively handles RichSnippets Product and Breadcrumb. For additional types (AggregateRating, Review, ItemList), custom JSON-LD injection in Twig is required. This markup enables Google to display rich snippets (price, reviews) and allows LLMs to extract structured product data for their recommendations.',
    geoScore:
      'The <strong>Rankwell GEO Score</strong> measures the citability of your Sylius store by AI engines on a scale of 0 to 100. It evaluates three dimensions: Informational Universe (depth of product pages, buying guides, and editorial content), Legitimacy and Citability (external trust signals, e-commerce backlinks, mentions on comparison sites), and Factual Density (richness of schema.org Product/Offer markup, verifiable technical data on product pages).',
    glossaryLinks: [
      { label: 'What is GEO?', href: '/en/glossary/geo' },
      { label: 'GEO audit: full methodology', href: '/en/glossary/audit-geo' },
    ],
  },

  // ============================================
  // BLOC 7: FAQ (plain text, no HTML)
  // ============================================
  faq: {
    title: 'Frequently asked questions: Sylius SEO',
    items: [
      {
        question: 'How much does Sylius SEO cost?',
        answer:
          'The SEO budget for a Sylius store depends on catalog size, front-end architecture (monolithic or decoupled), and whether SEO plugins are already installed. At Rankwell, Sylius SEO engagements start from $2,200/month for a store with fewer than 500 products, and range from $4,500 to $9,000/month for large catalogs with a decoupled Nuxt.js or Next.js front end. The budget is higher than for a CMS with native SEO because every technical component must be custom-built or configured from scratch.',
      },
      {
        question: 'How long does it take to see SEO results on Sylius?',
        answer:
          'Building the missing SEO layer (Dedi SEO plugins, sitemap, schema.org, SSR) takes 4 to 8 weeks. Initial indexation improvements appear within the first month after sitemap and SSR deployment. Ranking on competitive keywords requires 4 to 8 months of sustained effort, including content creation and link building. Rankwell provides a forecast timeline based on the initial technical audit of your Symfony installation.',
      },
      {
        question: 'Should I choose Dedi SEO or BetterSEO for Sylius?',
        answer:
          'The Dedi SEO plugin (by the Dedi agency) offers the most comprehensive coverage: meta tags, OpenGraph, RichSnippets Product and Breadcrumb, plus Google Analytics and Tag Manager integration. BetterSEO by JoppeDC focuses on product rich snippets and SEO-friendly images. Rankwell generally recommends Dedi SEO as the foundation, complemented by Stefan Doorn\\\'s Sitemap Plugin and custom JSON-LD injections in Twig for schema.org types not covered by the plugin.',
      },
      {
        question: 'How do I handle SEO for a decoupled Sylius SPA front end?',
        answer:
          'A decoupled front end built with React or Vue that does not perform server-side rendering (SSR) produces empty HTML for Googlebot, which prevents indexation. Rankwell configures SSR via Nuxt.js (Vue) or Next.js (React) so that every product and category page is rendered server-side with schema.org markup injected in the initial HTML. Static pre-rendering (SSG) is recommended for stable catalog pages.',
      },
      {
        question: 'How can I get my Sylius store cited by ChatGPT and Perplexity?',
        answer:
          'For AI engines to cite your products, three conditions must be met: product pages containing verifiable factual data (technical specifications, comparisons, pricing), complete Product + Offer schema.org markup injected in JSON-LD, and brand mentions on comparison sites and third-party media. The Rankwell GEO Score measures these three dimensions and identifies the priority levers to increase the citability of your product pages.',
      },
      {
        question: 'Is Sylius a good choice for e-commerce SEO in 2026?',
        answer:
          'Sylius offers maximum flexibility thanks to Symfony and API Platform, but its SEO must be built entirely from scratch. For a technical team capable of maintaining the architecture, it is an excellent choice: total control over HTML, routes, and structured markup surpasses what PrestaShop or Magento offer natively. For a team without a Symfony developer, the SEO setup cost may exceed that of a CMS with built-in SEO features. Rankwell adapts its methodology to each context.',
      },
      {
        question: 'Why choose Rankwell for Sylius SEO?',
        answer:
          'Rankwell combines e-commerce technical SEO expertise (Symfony audit, Dedi SEO/BetterSEO plugins, Product/Offer markup, SSR) with the GEO dimension that the vast majority of Sylius SEO agencies do not integrate. Our 8-step methodology includes building the complete SEO layer that Sylius does not provide natively. The proprietary GEO Score measures the visibility of your products across AI engines, a critical advantage for e-commerce in 2026.',
      },
    ],
  },

  // ============================================
  // CTA + Internal linking
  // ============================================
  cta: {
    title: 'Ready to optimize your Sylius store?',
    description:
      'Request a free GEO & SEO audit of your Sylius store. Our SEO & GEO consultants analyze your Symfony architecture, your plugins, your structured markup, and your AI engine visibility, and deliver a concrete action plan.',
    buttonText: 'Request a free audit',
    buttonHref: '/en/contact',
    relatedPages: {
      secteurs: [
        { label: 'SEO for Industry', href: '/en/geo-seo-agency/sector/industrie' },
        { label: 'SEO for Startups', href: '/en/geo-seo-agency/sector/startup' },
        { label: 'SEO for SMBs', href: '/en/geo-seo-agency/sector/pme' },
      ],
      projets: [
        { label: 'E-commerce SEO', href: '/en/geo-seo-agency/project/ecommerce' },
        { label: 'Marketplace SEO', href: '/en/geo-seo-agency/project/marketplace' },
        { label: 'Website Redesign SEO', href: '/en/geo-seo-agency/project/refonte' },
      ],
      cms: [
        { label: 'PrestaShop SEO', href: '/en/geo-seo-agency/cms/prestashop' },
        { label: 'Magento SEO', href: '/en/geo-seo-agency/cms/magento' },
        { label: 'WooCommerce SEO', href: '/en/geo-seo-agency/cms/woocommerce' },
      ],
      glossaire: [
        { label: 'E-commerce SEO', href: '/en/glossary/seo-ecommerce' },
        { label: 'Structured Data (Schema.org)', href: '/en/glossary/donnees-structurees' },
        { label: 'Technical SEO', href: '/en/glossary/seo-technique' },
      ],
    },
  },

  // Related CMS links
  relatedSectors: {
    title: 'SEO & GEO by CMS and platform',
    items: [
      { label: 'PrestaShop', href: '/en/geo-seo-agency/cms/prestashop' },
      { label: 'Magento', href: '/en/geo-seo-agency/cms/magento' },
      { label: 'WooCommerce', href: '/en/geo-seo-agency/cms/woocommerce' },
      { label: 'Shopify', href: '/en/geo-seo-agency/cms/shopify' },
      { label: 'OpenCart', href: '/en/geo-seo-agency/cms/opencart' },
    ],
  },
};

export default data;
