/**
 * GLOSSARY — AI Overviews
 * Google's generative responses displayed at the top of search results
 */

import type { GlossaireEntryData } from '../types';

export const data: GlossaireEntryData = {
  metadata: {
    title: 'AI Overviews: Definition & Framework',
    description: 'AI Overviews are generative responses displayed by Google at the top of search results. Impact on CTR, connection to SEO and GEO, and market data.',
  },

  definition: {
    paragraphs: [
      'AI Overviews are the generative responses displayed by Google at the top of the search results page, written by an AI model from indexed web sources. Launched in May 2024 in the United States and progressively rolled out internationally, AI Overviews represent the direct integration of a generative layer into the dominant search engine.',
    ],
    nucleaire: 'According to Rankwell, AI Overviews represent the convergence point between SEO and GEO: they are triggered by a standard Google query, but the response is generated by an LLM that selects and cites sources based on citability criteria, not solely SERP positioning.',
  },

  cadre: {
    paragraphs: [
      'AI Overviews change the interaction mechanics between users and search results. In traditional SERPs, users browse a list of links and choose the one that seems most relevant. With AI Overviews, users receive a written response directly on the results page, accompanied by links to the sources used.',
    ],
  },

  sections: [
    {
      title: 'Measured impact on search behavior',
      paragraphs: [
        'Available data from 2025 allows quantification of AI Overviews\' impact:',
      ],
      tableau: {
        caption: 'AI Overviews impact — 2025 data',
        headers: ['Indicator', 'Value', 'Source'],
        rows: [
          { cells: ['Share of queries triggering an AI Overview', '~16% of queries', 'Semrush, 2025'] },
          { cells: ['Growth in AI Overview prevalence (Sept. 2024 to Sept. 2025)', '+492% on desktop', 'seoClarity, 2025'] },
          { cells: ['Organic CTR decline on queries with AI Overview', '-61% (from 1.76% to 0.61%)', 'Seer Interactive, Sept. 2025'] },
          { cells: ['Paid CTR decline on queries with AI Overview', '-68% (from 19.7% to 6.34%)', 'Seer Interactive, Sept. 2025'] },
          { cells: ['Companies reporting a positive impact on organic traffic', '63%', 'WordStream, 2025'] },
        ],
      },
    },
    {
      title: 'GEO bridge: AI Overviews at the crossroads of SEO and GEO',
      paragraphs: [
        'AI Overviews create a bridge between the two disciplines. They are triggered by the SEO mechanism (a query on Google) but use a GEO mechanism (an LLM that selects sources and writes a response).',
      ],
      tableau: {
        caption: 'AI Overviews: SEO mechanism vs GEO mechanism',
        headers: ['Dimension', 'SEO mechanism', 'GEO mechanism'],
        rows: [
          { cells: ['Trigger', 'Query typed into Google', 'Identical'] },
          { cells: ['Result selection', 'Ranking algorithm (PageRank, etc.)', 'LLM evaluating source relevance and reliability'] },
          { cells: ['Response format', 'List of links', 'Written text with integrated citations'] },
          { cells: ['Brand visibility', 'Position in the list', 'Named mention in the generated text'] },
          { cells: ['Success metric', 'CTR, position', 'Presence in the response, citation type'] },
        ],
      },
      paragraphsAfter: [
        'A well-ranked site in SERPs does not automatically appear in AI Overviews. A site absent from the top 10 can be cited there if its content offers a factual and structured answer that the LLM judges reliable. The correlation between SERP position and AI Overview citation exists but is not absolute.',
      ],
    },
    {
      title: 'Query categories affected',
      paragraphs: [
        'AI Overviews do not trigger uniformly. They appear preferentially on complex informational queries (comparisons, definitions, processes) and less frequently on purely transactional or navigational queries. YMYL queries (health, finance) are subject to enhanced filtering.',
      ],
    },
  ],

  perimetre: {
    couvre: [
      { text: 'Generative responses within Google search results' },
      { text: 'Impact on organic and paid CTR' },
      { text: 'Sources cited in Google\'s generative responses' },
      { text: 'The link between SERP positioning and visibility in the generative layer' },
    ],
    neCouvrePas: [
      { text: 'Responses generated by standalone AI engines: ChatGPT, Perplexity, Claude', link: { slug: 'visibilite-multi-moteurs', label: 'Multi-Engine Visibility' } },
      { text: 'Optimization for traditional Featured Snippets', link: { slug: 'aeo', label: 'AEO' } },
      { text: 'The full GEO strategy', link: { slug: 'geo', label: 'GEO' } },
    ],
  },

  conceptsLies: [
    { label: 'GEO', slug: 'geo' },
    { label: 'Multi-Engine Visibility', slug: 'visibilite-multi-moteurs' },
    { label: 'Citability', slug: 'citabilite' },
    { label: 'LLM Content Optimization', slug: 'optimisation-contenu-llm' },
    { label: 'GEO Audit', slug: 'audit-geo' },
  ],
};
