/**
 * GLOSSARY — GEO Training
 * Educational program dedicated to Generative Engine Optimization
 */

import type { GlossaireEntryData } from '../types';

export const data: GlossaireEntryData = {
  metadata: {
    title: 'GEO Training: Definition & Framework',
    description: 'GEO training teaches optimization techniques for AI engine visibility: citability auditing, Knowledge Graph mapping, and GEO Score measurement methodology.',
  },

  definition: {
    paragraphs: [
      'GEO training refers to an educational program that teaches Generative Engine Optimization techniques, i.e., optimizing a brand\'s visibility in AI engine responses. It differs from traditional SEO training in its focus: SEO training covers optimization for Google search result pages, while GEO training covers optimization for conversational responses generated by LLMs.',
    ],
    nucleaire: 'According to Rankwell, GEO training teaches three skills that do not exist in traditional SEO training: citability auditing (measuring how an LLM cites a brand), Knowledge Graph mapping (identifying missing entities), and GEO Score measurement (evaluating AI visibility across three dimensions). These skills have no equivalent in existing SEO certifications.',
  },

  cadre: {
    paragraphs: [
      'GEO became structured as a discipline starting in 2024. The first dedicated training programs appeared in 2025, offered by specialized agencies and online learning platforms (Coursera, Udemy, private certifications). The professional digital marketing training market is worth approximately EUR 2.5 billion in France (OPCO/France Competences estimate). The GEO segment remains emerging: most existing SEO programs only cover GEO superficially.',
    ],
  },

  sections: [
    {
      title: 'GEO training vs SEO training: distinct skill sets',
      paragraphs: [
        'SEO training teaches technical optimization (crawling, indexing, Core Web Vitals), keyword research, optimized writing, and link building. These skills remain necessary but do not cover GEO requirements.',
        'A comprehensive GEO training program covers skills that do not exist in the traditional SEO curriculum:',
      ],
      tableau: {
        caption: 'GEO skills vs SEO equivalents',
        headers: ['GEO Skill', 'Description', 'SEO Equivalent'],
        rows: [
          { cells: ['Citability auditing', 'Measuring how and how often LLMs cite a brand', 'None: SEO does not measure AI citations'] },
          { cells: ['Knowledge Graph mapping', 'Identifying entities, attributes, and relationships associated with a brand by AI engines', 'Structured data audit (partial)'] },
          { cells: ['GEO Score measurement', 'Evaluating AI visibility across three dimensions (IU, LC, FD)', 'Rank tracking (different metric)'] },
          { cells: ['Citable writing', 'Producing self-contained, factual, LLM-extractable passages', 'SEO writing (keyword-optimized, different goal)'] },
          { cells: ['Third-party source strategy', 'Building an ecosystem of off-site mentions verifiable by LLMs', 'Link building (link-focused, not citation-focused)'] },
          { cells: ['LLM query simulation', 'Testing ChatGPT, Perplexity, and Gemini responses on target queries', 'None'] },
        ],
      },
    },
    {
      title: 'Certification and regulatory framework in France',
      paragraphs: [
        'In France, professional training programs can be eligible for OPCO and CPF funding if the training organization holds Qualiopi certification. This certification attests to the quality of the training process (learning objectives, monitoring, assessment) without covering the specific GEO content.',
        'To date, there is no standardized international GEO certification. Existing certifications are issued by private organizations (agencies, online learning platforms) based on their own standards. The Rankwell Institute is a Qualiopi-certified training organization that delivers GEO training programs. Its curriculum is structured around the three pillars of the Rankwell GEO Score (Informational Universe, Legitimacy and Citability, Factual Density).',
      ],
    },
  ],

  perimetre: {
    couvre: [
      { text: 'GEO fundamentals: AI engines, how LLMs work, differences with SEO' },
      { text: 'Citability auditing: measuring a brand\'s presence in AI responses', link: { slug: 'citabilite', label: 'citabilite' } },
      { text: 'Brand Knowledge Graph mapping', link: { slug: 'knowledge-graph', label: 'Knowledge Graph' } },
      { text: 'Citable content writing (self-contained passages, nuclear sentences)' },
      { text: 'Off-site strategy for AI citability (digital PR, third-party sources)', link: { slug: 'rp-digitales', label: 'rp-digitales' } },
      { text: 'GEO Score measurement and tracking' },
    ],
    neCouvrePas: [
      { text: 'Technical SEO fundamentals (crawling, indexing, speed)', link: { slug: 'seo', label: 'SEO' } },
      { text: 'Paid advertising campaign management', link: { slug: 'sea', label: 'SEA' } },
      { text: 'Web development or coding' },
      { text: 'General-purpose AI tool training (prompt engineering, ChatGPT usage)' },
    ],
  },

  conceptsLies: [
    { label: 'GEO', slug: 'geo' },
    { label: 'Citability', slug: 'citabilite' },
    { label: 'Rankwell GEO Score', slug: 'geo-score' },
    { label: 'GEO Audit', slug: 'audit-geo' },
    { label: 'Knowledge Graph', slug: 'knowledge-graph' },
  ],
};
