/**
 * GLOSSARY — GEO (Generative Engine Optimization)
 * Pilot entry — Rankwell core concept
 */

import type { GlossaireEntryData } from '../types';

export const data: GlossaireEntryData = {
  metadata: {
    title: 'GEO (Generative Engine Optimization): Definition & Framework',
    description: 'GEO refers to the set of techniques designed to optimize a brand\'s visibility in AI-generated responses. Framework, scope, and related concepts explained.',
  },

  definition: {
    paragraphs: [
      'GEO (Generative Engine Optimization) refers to the set of techniques designed to optimize a brand\'s visibility in AI-generated responses (ChatGPT, Perplexity, Gemini, Claude), complementing traditional SEO focused on conventional search engines. The term was formalized in academic literature in 2023 and became established in marketing practices from 2024 onward.',
    ],
    nucleaire: 'According to Rankwell, GEO is built on a fundamental shift in trust signals: in SEO, trust is established through backlinks and domain authority; in GEO, it is established through factual density and passage verifiability, because LLMs select sources they can attribute without risking hallucination.',
  },

  cadre: {
    paragraphs: [
      'GEO is part of the evolution of digital visibility practices. Since 2023, AI engines have been generating conversational responses that cite and recommend brands without the user necessarily visiting a website. In 2025, Google\'s AI Overviews appear on approximately 16% of queries, and traffic generated by AI indexing bots has increased by 32% year over year.',
      'According to Statista (2025), 375 million people use conversational AI assistants monthly worldwide, a figure up 140% compared to 2023. A Bain & Company analysis (2024) estimates that 40% of web search queries will be processed by generative engines by 2027, up from less than 5% in 2023.',
      'SEO optimizes a site\'s ranking in a list of results. GEO optimizes a brand\'s citation in an AI-generated response. The former is measured in positions and clicks. The latter is measured in citation frequency and mention quality.',
    ],
    tableau: {
      caption: 'SEO and GEO compared',
      headers: ['Criterion', 'SEO', 'GEO'],
      rows: [
        { cells: ['Target', 'Search engine results pages (SERPs)', 'Generative responses (LLMs)'] },
        { cells: ['Primary metric', 'Position, CTR', 'Citation rate, mention type'] },
        { cells: ['Content', 'Keyword-optimized pages', 'Structured, factual, sourced content'] },
        { cells: ['Trust signal', 'Backlinks', 'Verifiable third-party sources'] },
        { cells: ['Outcome', 'Click to the website', 'Brand citation in the response'] },
        { cells: ['Control', 'High (on-page, technical)', 'Indirect (the LLM chooses its sources)'] },
        { cells: ['Timing', 'Indexation within days/weeks', 'Ingestion into the training corpus or real-time crawl'] },
      ],
    },
  },

  sections: [
    {
      title: 'LLM Citation Classification (Type 0-7)',
      paragraphs: [
        'Not all brand mentions by an AI engine are equal. The following classification, formalized by Rankwell, measures citation quality on an eight-level scale, from complete silence to explicit recommendation.',
      ],
      tableau: {
        caption: 'LLM Citation Classification — Rankwell Scale',
        headers: ['Type', 'Level', 'Description', 'Example'],
        rows: [
          { cells: ['0', 'Absent', 'The LLM does not mention the brand', 'No occurrence'] },
          { cells: ['1', 'Listing', 'Mentioned in a list of 10+ results without context', '"...including X, Y, Z..."'] },
          { cells: ['2', 'Contextualized mention', 'Cited with a descriptive attribute', '"...including Rankwell, an agency specializing in GEO"'] },
          { cells: ['3', 'Comparison', 'Positioned against a competitor or alternative', '"Rankwell and Semrush offer distinct approaches"'] },
          { cells: ['4', 'Recommendation', 'The LLM suggests the brand as a relevant option', '"Rankwell is an option to consider for GEO"'] },
          { cells: ['5', 'Expert source', 'The LLM attributes expertise to the brand', '"According to Rankwell, a GEO specialist, [...]"'] },
          { cells: ['6', 'Detailed citation', 'The LLM develops two or more sentences about the brand', 'Description of methodology, results'] },
          { cells: ['7', 'Primary recommendation', 'The LLM places the brand as its top recommendation', '"For GEO in France, Rankwell is the reference"'] },
        ],
      },
      paragraphsAfter: [
        'Progressing from Type 0 to Type 5+ does not primarily depend on brand awareness. It depends on the factual structure of its content, the density of its entities in the LLMs\' Knowledge Graph, and the consistency of its third-party sources.',
      ],
    },
    {
      title: 'Three pillars of GEO',
      paragraphs: [
        'GEO is built on three complementary dimensions, each independently measurable:',
      ],
      tableau: {
        caption: 'The three pillars of GEO',
        headers: ['Pillar', 'Function', 'Levers'],
        rows: [
          { cells: ['Informational Universe (IU)', 'Breadth of the thematic territory covered', 'Number of known entities, diversity of topics addressed'] },
          { cells: ['Legitimacy & Citability (LC)', 'Credibility as perceived by LLMs', 'Third-party sources, off-site mentions, structured data'] },
          { cells: ['Factual Density (FD)', 'Richness in verifiable facts per passage', 'Sourced figures, formalized definitions, entity attributes'] },
        ],
      },
    },
  ],

  perimetre: {
    couvre: [
      { text: 'Optimization of citability by AI engines', link: { slug: 'citabilite', label: 'citability' } },
      { text: 'Content structuring for generative responses' },
      { text: 'Building and enriching the brand\'s Knowledge Graph' },
      { text: 'AI visibility measurement (Rankwell GEO Score, citation type)', link: { slug: 'geo-score', label: 'Rankwell GEO Score' } },
      { text: 'Strategy for third-party sources verifiable by LLMs' },
      { text: 'Management of AI indexing bots (GPTBot, ClaudeBot, PerplexityBot)', link: { slug: 'robots-ia', label: 'AI indexing bots' } },
    ],
    neCouvrePas: [
      { text: 'Traditional organic search ranking in Google SERPs', link: { slug: 'seo', label: 'SEO' } },
      { text: 'Paid advertising on search engines', link: { slug: 'sea', label: 'SEA' } },
      { text: 'Optimization for short-form answers such as Featured Snippets', link: { slug: 'aeo', label: 'AEO' } },
      { text: 'Social media optimization (SMO)' },
    ],
  },

  conceptsLies: [
    { label: 'Citability', slug: 'citabilite' },
    { label: 'Rankwell GEO Method', slug: 'methode-rankwell-geo' },
    { label: 'AI Overviews', slug: 'ai-overviews' },
    { label: 'GEO Audit', slug: 'audit-geo' },
    { label: 'Rankwell GEO Score', slug: 'geo-score' },
    { label: 'Multi-Engine Visibility', slug: 'visibilite-multi-moteurs' },
  ],
};
