/**
 * GLOSSARY — Google Ads
 * Google advertising platform, Search/Shopping/Display/PMax campaigns
 */

import type { GlossaireEntryData } from '../types';

export const data: GlossaireEntryData = {
  metadata: {
    title: 'Google Ads: Definition & Framework',
    description: 'Google Ads is Google\'s advertising platform for running paid ads across Search, Shopping, Display, YouTube, and Performance Max campaign types.',
  },

  definition: {
    paragraphs: [
      'Google Ads is Google\'s advertising platform that allows advertisers to run paid ads on the Google Search network, the Display network (partner sites), YouTube, Gmail, Google Maps, and Google Shopping. Launched in 2000 as Google AdWords, the platform was rebranded to Google Ads in 2018. It operates on a real-time auction model, primarily on a cost-per-click (CPC) basis.',
      'Google Ads generated $307 billion USD in revenue in 2024, representing approximately 80% of Alphabet\'s total revenue (2024 annual report). The average CPC in France is approximately EUR 1 to 2 across all sectors, but can exceed EUR 50 in sectors like insurance or legal.',
    ],
    nucleaire: 'According to Rankwell, Google Ads is the operational tool of SEA, but its sphere of influence stops at purchased ad placements: Google Ads campaigns do not feed Google\'s Knowledge Graph or LLM training data. A site that is invisible in organic results but active on Ads remains invisible to ChatGPT and Perplexity. Investing in Google Ads provides visibility in paid SERPs, not in generative responses.',
  },

  cadre: {
    paragraphs: [
      'Google Ads structures its campaigns by type, each corresponding to a distribution network and a specific ad format. The choice of campaign type depends on the objective (awareness, traffic, conversion, online sales) and the industry.',
    ],
    tableau: {
      caption: 'Google Ads campaign types',
      headers: ['Type', 'Distribution Network', 'Format', 'Use Case'],
      rows: [
        { cells: ['Search', 'Google search results', 'Text ads (headlines + descriptions)', 'Capturing active search intent'] },
        { cells: ['Shopping', 'Shopping tab + search results', 'Product cards with image, price, merchant name', 'E-commerce, online sales'] },
        { cells: ['Display', 'Google Display Network partner sites (2M+ sites)', 'Visual banners, responsive ads', 'Awareness, retargeting'] },
        { cells: ['Video', 'YouTube', 'Video ads (in-stream, bumper, in-feed)', 'Awareness, consideration'] },
        { cells: ['Performance Max', 'All Google networks simultaneously', 'Multi-format (text, image, video) generated by AI', 'Cross-channel conversion maximization'] },
        { cells: ['Demand Gen', 'YouTube, Discover, Gmail', 'Immersive visuals', 'Demand generation, cold audiences'] },
      ],
    },
  },

  sections: [
    {
      title: 'Performance Max and AI automation',
      paragraphs: [
        'Performance Max (PMax), launched in 2021, is Google Ads\' most automated campaign type. The advertiser provides "asset groups" (headlines, descriptions, images, videos, destination URLs) and Google automatically generates the best-performing ad combinations, distributed across all networks.',
        'In 2025-2026, Google enhanced PMax transparency: network-level reports are now more detailed, and advertisers have greater control levers (campaign-level keyword exclusions, expanded search terms reports). Google also introduced "AI Max for Search," which applies AI automation capabilities to standard Search campaigns (automatic search term expansion, dynamic ad creation).',
      ],
    },
    {
      title: 'Google Ads and AI Overviews',
      paragraphs: [
        'Google\'s AI Overviews display generative responses at the top of certain SERPs. Google inserts ad placements when the query shows commercial intent. Shopping and Search ads can appear within the context of a Google-generated AI response, labeled "Sponsored."',
        'This mechanism is exclusive to the Google ecosystem. Third-party AI engines (ChatGPT, Perplexity, Claude) do not display Google Ads in their responses. The visibility gained through Google Ads in AI Overviews depends on campaign eligibility and the query, and does not transfer to other AI engines.',
      ],
    },
    {
      title: 'Key metrics',
      tableau: {
        caption: 'Key Google Ads metrics',
        headers: ['Metric', 'Definition', 'Usage'],
        rows: [
          { cells: ['CPC (Cost Per Click)', 'Price paid for each click on the ad', 'Traffic acquisition cost control'] },
          { cells: ['CTR (Click-Through Rate)', 'Clicks / Impressions', 'Ad relevance evaluation'] },
          { cells: ['Quality Score', 'Score from 1-10 assigned by Google (relevance, landing page, expected CTR)', 'Cost and positioning optimization'] },
          { cells: ['ROAS (Return on Ad Spend)', 'Revenue generated / Ad spend', 'Campaign profitability measurement'] },
          { cells: ['Conversion rate', 'Conversions / Clicks', 'Landing page effectiveness evaluation'] },
        ],
      },
    },
  ],

  perimetre: {
    couvre: [
      { text: 'Creating and managing advertising campaigns across Google networks' },
      { text: 'Search, Shopping, Display, Video, Performance Max, and Demand Gen formats' },
      { text: 'The CPC, CPM, and CPA auction system' },
      { text: 'Targeting by keywords, audiences, placements, and demographics' },
      { text: 'Appearing in Google AI Overviews (sponsored placements)' },
    ],
    neCouvrePas: [
      { text: 'Organic positioning in Google results', link: { slug: 'seo', label: 'SEO' } },
      { text: 'Visibility in third-party AI engine responses', link: { slug: 'geo', label: 'GEO' } },
      { text: 'Social media advertising (Meta Ads, LinkedIn Ads)' },
      { text: 'Overall multi-platform paid search strategy', link: { slug: 'sea', label: 'SEA' } },
    ],
  },

  conceptsLies: [
    { label: 'SEA', slug: 'sea' },
    { label: 'SEO', slug: 'seo' },
    { label: 'GEO', slug: 'geo' },
    { label: 'Core Web Vitals', slug: 'core-web-vitals' },
    { label: 'Knowledge Graph', slug: 'knowledge-graph' },
    { label: 'AI Overviews', slug: 'ai-overviews' },
  ],
};
