/**
 * GLOSSARY — Knowledge Panel
 * Structured information box in Google SERPs
 */

import type { GlossaireEntryData } from '../types';

export const data: GlossaireEntryData = {
  metadata: {
    title: 'Knowledge Panel: Definition & Framework',
    description: 'A Knowledge Panel is the structured information box displayed in Google SERPs for an identified entity. Triggers, claiming process, and link to AI visibility.',
  },

  definition: {
    paragraphs: [
      'A Knowledge Panel is the structured information box that appears in Google search results when an entity (person, company, place, concept) is identified with certainty in Google\'s Knowledge Graph. The Knowledge Panel aggregates data from multiple sources (Wikidata, Wikipedia, official website, Google Business Profile, third-party sources) and presents them as a summary card to the right of search results on desktop, or in a prominent position on mobile.',
    ],
    nucleaire: 'According to Rankwell, the Knowledge Panel is an indirect indicator of AI citability. An entity that has a Knowledge Panel is more likely to be cited by LLMs, not because LLMs access Google\'s Knowledge Graph, but because the same public sources that feed the Knowledge Graph (Wikidata, Wikipedia, consistent third-party mentions) are also those that LLMs ingest in their training corpora. If a Knowledge Panel exists, the underlying data is probably in the LLMs\' corpora.',
  },

  cadre: {
    paragraphs: [
      'The Knowledge Panel is automatically generated by Google from its Knowledge Graph, which contains over 500 billion facts about more than 5 billion entities (Google I/O, 2023). An entity gets a Knowledge Panel when Google has enough concordant data from independent sources to confirm its existence and attributes (name, type, description, official website, social profiles).',
    ],
  },

  sections: [
    {
      title: 'How to obtain a Knowledge Panel',
      paragraphs: [
        'Obtaining a Knowledge Panel is not a direct request process. Google generates the panel when the entity reaches a threshold of notability and data consistency.',
      ],
      tableau: {
        caption: 'Knowledge Panel trigger factors',
        headers: ['Factor', 'Description', 'Associated action'],
        rows: [
          { cells: ['Wikidata presence', 'The entity has a Wikidata item with populated properties', 'Create or enrich the entity\'s Wikidata item'] },
          { cells: ['Wikipedia page', 'A Wikipedia article exists for the entity', 'The article must meet Wikipedia\'s notability criteria'] },
          { cells: ['Data consistency', 'The name, type, and attributes are consistent across sources', 'Consistent NAP, Schema.org on the site, aligned social profiles'] },
          { cells: ['Structured data', 'The official website uses Schema.org (Organization, Person, LocalBusiness)', 'JSON-LD markup with key properties'] },
          { cells: ['Third-party mentions', 'The entity is mentioned by independent, authoritative sources', 'Press relations, industry publications, professional directories'] },
          { cells: ['Google Business Profile', 'For local businesses, the GBP is verified and complete', 'Complete all information, add photos, collect reviews'] },
        ],
      },
    },
    {
      title: 'Claiming and optimizing a Knowledge Panel',
      paragraphs: [
        'Google allows verified entities to claim their Knowledge Panel through the Google Search verification process, available since 2019. Once claimed, the entity can suggest edits (correcting information, adding social profiles, modifying the description). Google is not obligated to accept these suggestions: the panel remains under algorithmic control.',
        'Jason Barnard (Kalicube) has formalized the concept of "digital brand SERP" around the Knowledge Panel, defining the panel as the pivot of a brand\'s digital identity management in Google results.',
      ],
    },
    {
      title: 'Knowledge Panel and AI Overviews',
      paragraphs: [
        'The Knowledge Panel directly feeds Google\'s AI Overviews. When a user asks a question about an entity with a Knowledge Panel, AI Overviews use Knowledge Graph data to structure their response. An entity with a rich and accurate Knowledge Panel is more likely to see its information accurately reflected in Google\'s generative responses.',
        'This link is bidirectional: the Knowledge Graph data that feeds the Knowledge Panel is the same data used by Google\'s AI systems to generate responses. Third-party LLMs (ChatGPT, Claude, Perplexity) do not have access to Google\'s Knowledge Graph, but they access the same public sources (Wikidata, Wikipedia, official websites) that feed this Knowledge Graph. An entity well-represented in these sources is therefore visible both in Google\'s Knowledge Panel and in third-party LLM responses.',
      ],
    },
    {
      title: 'Knowledge Panel and Knowledge Graph: distinction',
      paragraphs: [
        'The Knowledge Graph is Google\'s entity and relationship database. The Knowledge Panel is the surface display of an entry in that graph. The Knowledge Graph is invisible to users. The Knowledge Panel is the visible interface. A site can be present in the Knowledge Graph (Google knows the entity) without triggering a Knowledge Panel (the notability threshold has not been reached).',
      ],
    },
  ],

  perimetre: {
    couvre: [
      { text: 'The structured information box in Google search results' },
      { text: 'Trigger factors (notability, data consistency, Wikidata)' },
      { text: 'The claiming and edit suggestion process' },
      { text: 'The link with AI Overviews and AI visibility' },
    ],
    neCouvrePas: [
      { text: 'Building Google\'s Knowledge Graph (internal system, not accessible)' },
      { text: 'Detailed Schema.org markup', link: { slug: 'donnees-structurees', label: 'Données structurées' } },
      { text: 'Local listing optimization', link: { slug: 'optimisation-de-la-fiche-google-my-business-gmb', label: 'Optimisation Google My Business' } },
      { text: 'Sitelinks in search results', link: { slug: 'sitelinks', label: 'Sitelinks' } },
    ],
  },

  conceptsLies: [
    { label: 'Données structurées', slug: 'donnees-structurees' },
    { label: 'E-E-A-T', slug: 'e-e-a-t' },
    { label: 'Knowledge Graph', slug: 'knowledge-graph' },
    { label: 'Optimisation Google My Business', slug: 'optimisation-de-la-fiche-google-my-business-gmb' },
    { label: 'Sitelinks', slug: 'sitelinks' },
    { label: 'GEO', slug: 'geo' },
  ],
};
