/**
 * GLOSSARY — E-commerce SEO
 * Search engine optimization for online stores
 */

import type { GlossaireEntryData } from '../types';

export const data: GlossaireEntryData = {
  metadata: {
    title: 'E-commerce SEO: Definition & Framework',
    description: 'E-commerce SEO covers optimization techniques for online stores: product pages, faceted navigation, Product structured data, and LLM product recommendations.',
  },

  definition: {
    paragraphs: [
      'E-commerce SEO refers to all search engine optimization techniques applied to online retail websites. E-commerce SEO addresses challenges specific to product catalogs: product and category pages, faceted navigation, duplicate content generated by variants, Product structured data, and crawl management on high-volume sites.',
    ],
    nucleaire: 'According to Rankwell, e-commerce SEO in 2026 integrates an unprecedented challenge: LLMs are becoming a full-fledged product recommendation channel. ChatGPT and Perplexity compare products, recommend brands, and cite product pages in their responses, relying on the factual density of pages (specifications, reviews, comparisons) and information verifiability.',
  },

  cadre: {
    paragraphs: [
      'E-commerce SEO differs from editorial SEO in the nature of its pages: product listings are often auto-generated, categories multiply filtered URLs, and pagination creates crawl budget issues. According to Fevad (E-commerce Report 2024), French e-commerce revenue reached 159.9 billion euros in 2023, and the organic channel accounts for an average of 33% of e-commerce site traffic according to a SEMrush study (2023). Product structured data (price, availability, reviews) has become a prerequisite for rich results in SERPs and Google Shopping tabs.',
      'In 2025, Aleyda Solis documented the convergence between Google Merchant Center feeds and on-page structured data: both sources must be consistent to maximize visibility in Google product results. Product variants (size, color) now benefit from dedicated structured markup (ProductGroup, hasVariant) that helps engines understand relationships between pages without treating them as duplicate content.',
    ],
  },

  sections: [
    {
      title: 'LLMs as a product recommendation channel',
      paragraphs: [
        'AI engines increasingly respond to purchase queries: "which robot vacuum to choose in 2026?", "best mattress for back pain." These responses cite products and brands based on criteria different from Google Shopping.',
      ],
      tableau: {
        caption: 'Google Shopping vs LLM recommendation',
        headers: ['Criterion', 'Google Shopping / SERP', 'LLM recommendation'],
        rows: [
          { cells: ['Data source', 'Merchant Center + structured data', 'Crawled page content + third-party sources'] },
          { cells: ['Key factor', 'Price, availability, Google reviews', 'Factual density, specifications, verifiable comparisons'] },
          { cells: ['Preferred format', 'Product page with Product markup', 'Attribute-rich text content (material, dimensions, performance)'] },
          { cells: ['Reviews', 'Aggregated Google rating', 'Detailed reviews on third-party sites (Trustpilot, specialized forums)'] },
        ],
      },
      paragraphsAfter: [
        'A product page containing only a title, a price, and three marketing bullet points has little chance of being cited by an LLM. Pages rich in factual attributes (composition, dimensions, certifications, manufacturing conditions) and editorial content (buying guides, integrated comparisons) concentrate citations.',
      ],
    },
    {
      title: 'E-commerce-specific optimizations',
      tableau: {
        caption: 'E-commerce issues and SEO/GEO solutions',
        headers: ['Issue', 'SEO solution', 'AI citability impact'],
        rows: [
          { cells: ['Duplicate content (variants)', 'Canonical tags + ProductGroup/hasVariant', 'Reduces dilution, structures product entities'] },
          { cells: ['Faceted navigation', 'URL parameter management (noindex, canonical, robots.txt)', 'Limits unnecessary crawling by AI bots'] },
          { cells: ['Thin category pages', 'Enriched editorial content (guides, FAQ, comparisons)', 'Increases citable factual density'] },
          { cells: ['Generic product pages', 'Unique descriptions with detailed factual attributes', 'Multiplies extractable passages for LLMs'] },
          { cells: ['Customer reviews', 'Review + AggregateRating markup', 'Trust signal for Google and raw material for LLMs'] },
        ],
      },
    },
  ],

  perimetre: {
    couvre: [
      { text: 'Product page optimization (content, structured data, images)' },
      { text: 'Category page and faceted navigation optimization' },
      { text: 'Crawl budget management on large catalogs' },
      { text: 'Product, Offer, AggregateRating, ProductGroup markup' },
      { text: 'E-commerce content strategy (buying guides, comparisons, FAQ)' },
      { text: 'Positioning as a recommendation source for LLMs' },
    ],
    neCouvrePas: [
      { text: 'Google Shopping and Google Ads campaigns', link: { slug: 'sea', label: 'SEA' } },
      { text: 'Amazon marketplace and third-party marketplace optimization' },
      { text: 'Local SEO for physical stores', link: { slug: 'seo-local', label: 'SEO local' } },
      { text: 'Overall brand AI citability optimization', link: { slug: 'geo', label: 'GEO' } },
    ],
  },

  conceptsLies: [
    { label: 'SEO', slug: 'seo' },
    { label: 'SEO technique', slug: 'seo-technique' },
    { label: 'Données structurées', slug: 'donnees-structurees' },
    { label: 'SEO sémantique', slug: 'seo-semantique' },
    { label: 'Migration SEO', slug: 'migration-seo' },
  ],
};
