/**
 * GLOSSARY — Multi-Engine Visibility
 * A brand's presence in responses across all AI engines
 */

import type { GlossaireEntryData } from '../types';

export const data: GlossaireEntryData = {
  metadata: {
    title: 'Multi-Engine Visibility: Definition & Framework',
    description: 'Multi-engine visibility refers to a brand\'s presence in responses across all AI engines (ChatGPT, Perplexity, Gemini, Claude, Copilot, AI Overviews).',
  },

  definition: {
    paragraphs: [
      'Multi-engine visibility refers to a brand\'s presence in the responses generated by all AI engines (Google AI Overviews, ChatGPT, Perplexity, Gemini, Claude, Copilot) rather than just one of them. Each AI engine uses a distinct language model, different data sources, and proprietary selection criteria.',
    ],
    nucleaire: 'According to Rankwell, multi-engine visibility is the direct corollary of GEO: optimizing for a single AI engine repeats the historical mistake of "Google-only" SEO in an ecosystem that, by 2025, already includes six AI engines generating responses from web sources.',
  },

  cadre: {
    paragraphs: [
      'Multi-engine visibility is rooted in the observation that the AI engine ecosystem is fragmented. Unlike SEO where Google holds over 90% market share in Europe, AI engines share use cases without any single player dominating across all scenarios.',
    ],
    tableau: {
      caption: 'Distinction: multi-engine vs multichannel',
      headers: ['Concept', 'Scope', 'Examples'],
      rows: [
        { cells: ['Multi-engine visibility', 'Generative responses from AI engines', 'ChatGPT, Perplexity, Gemini, Claude, Copilot, AI Overviews'] },
        { cells: ['Multichannel visibility', 'Digital marketing channels', 'SEO, SEA, social media, email marketing, display'] },
      ],
    },
  },

  sections: [
    {
      title: 'AI engine mapping (2025)',
      paragraphs: [
        'Each AI engine has a distinct profile that influences the type of content it cites and how it does so.',
      ],
      tableau: {
        caption: 'AI engine mapping in 2025',
        headers: ['AI Engine', 'Underlying model', 'Web source access', 'Citation mode', 'Usage profile'],
        rows: [
          { cells: ['Google AI Overviews', 'Gemini', 'Real-time Google index', 'Embedded sources with links', 'Standard search queries'] },
          { cells: ['ChatGPT (Search)', 'GPT-4o', 'GPTBot crawl + Bing search', 'Citations with links in the response', 'Conversational questions, search'] },
          { cells: ['Perplexity', 'Multiple models', 'PerplexityBot crawl + web search', 'Numbered citations with sources', 'In-depth factual research'] },
          { cells: ['Gemini', 'Gemini', 'Google index + web search', 'Responses with linked sources', 'Assistant integrated into the Google ecosystem'] },
          { cells: ['Claude', 'Claude', 'ClaudeBot crawl (limited)', 'Textual citations in the response', 'Analysis, writing, reasoning'] },
          { cells: ['Copilot (Microsoft)', 'GPT-4o', 'Bing index + web search', 'Numbered citations with sources', 'Search integrated into the Microsoft ecosystem'] },
        ],
      },
    },
    {
      title: 'Why content cited by one AI engine is not necessarily cited by another',
      paragraphs: [
        'An Authoritas study (2024) comparing sources cited by ChatGPT, Perplexity, and Gemini across 1,000 commercial queries measured an overlap rate of only 12%: only 12% of sources appeared in the responses of all three AI engines simultaneously. This result confirms that visibility on a single AI engine does not predict visibility on the others.',
      ],
      items: [
        { label: 'Data corpus', description: 'Each AI engine accesses a different set of sources. A site blocking GPTBot in robots.txt will not be indexed by ChatGPT but may be indexed by Perplexity if PerplexityBot is allowed.' },
        { label: 'Selection algorithm', description: 'The criteria determining which sources are cited vary from one model to another. Perplexity favors factual sources and cites them systematically. ChatGPT synthesizes more and cites less often.' },
        { label: 'Data freshness', description: 'Some engines crawl the web in real time (Perplexity, AI Overviews), while others integrate data with a lag tied to model training.' },
      ],
      paragraphsAfter: [
        'According to Gartner (2025), 70% of web searches will incorporate a generative component by the end of 2026, distributed across at least four distinct platforms (Google, OpenAI, Anthropic, Perplexity). This fragmentation reinforces the need for a multi-engine strategy from the content design stage.',
      ],
    },
  ],

  perimetre: {
    couvre: [
      { text: 'A brand\'s presence in the responses of each AI engine' },
      { text: 'Citation gaps between AI engines for the same query' },
      { text: 'The impact of AI indexing bots on multi-engine coverage', link: { slug: 'robots-ia', label: 'AI indexing bots' } },
      { text: 'Content strategy adapted to all AI engines' },
    ],
    neCouvrePas: [
      { text: 'Ranking in traditional Google or Bing SERPs', link: { slug: 'seo', label: 'SEO' } },
      { text: 'Optimization specific to Google AI Overviews', link: { slug: 'ai-overviews', label: 'AI Overviews' } },
      { text: 'Composite measurement of AI visibility', link: { slug: 'geo-score', label: 'Rankwell GEO Score' } },
    ],
  },

  conceptsLies: [
    { label: 'GEO', slug: 'geo' },
    { label: 'AI Overviews', slug: 'ai-overviews' },
    { label: 'AI Indexing Bots', slug: 'robots-ia' },
    { label: 'GEO Audit', slug: 'audit-geo' },
    { label: 'Citability', slug: 'citabilite' },
  ],
};
